### ISSUE TITLE
Freezes on nytimes.com

### ISSUE THREAD

**Issue by Wowfunhappy** [i3roly/firefox-dynasty#13]
On 10.9.5, when I visit nytimes.com in the latest version of Firefox Dynasty and scroll up and down the page for a minute or so, the browser freezes with a beachball.

I was able to replicate this in a clean VM.

When Firefox is launched via the Terminal, the Terminal output ends with the message `Exiting due to channel error.` printed multiple times. I've attached the full output.

[Firefox nytimes.com.txt](https://github.com/user-attachments/files/17248347/Firefox.nytimes.com.txt)

This isn't the best test case because it changes several times per day, but it is what it is.

**Comment by i3roly** [comment]
https://github.com/user-attachments/assets/22ff91e3-8c59-4ec4-b532-7b709d5bb89b

this is with vtdecoder disabled. something is going on with MP4 and vtdecoder. i will try to look into it, but worst case i may have to disable it for lower macs. i hope not though.

VTdecoder is supposed to be for hardware decoding, but if 78 can trigger it, then i dont' see why newer versions shouldn't do the same thing.

**Comment by Wowfunhappy** [comment]
FYI @i3roly, videos on the homepage of nytimes.com appear to be broken again in latest build. (But the browser doesn't freeze!)

**Comment by i3roly** [comment]
thanks for the heads up. i suspected i was trying to be too cute and got away with it before.

peep the updated release. it should be fixed.

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
Yes, fixed!
