### ISSUE TITLE
mixed results on latest version

### ISSUE THREAD

**Issue by MacBiter** [i3roly/firefox-dynasty#14]
I downloaded the newest release and there is both good and bad news.

The password issue I had (but no-one else!) is no longer a problem - the 'eyeball' works as it should.

Unfortunately, just about every new tab and site I loaded caused Dynasty to freeze, needing a force quit. At first I thought it was because every site I was loading streamed video, but the last one I tried was just a forum, and the same thing happened.

**Comment by i3roly** [comment]
you are banned from further issues. 

this is not a finding that you are a vexatious, frivolous or abusive litigant, but rather you must seek permission to post to verify your claims. i suggest engaging @wowfunhappy for verification of the issues, which can then be brought to my attention.

order shortly

**Comment by Wowfunhappy** [comment]
@i3roly I just quickly checked on the most recent build, and I'm actually seeing the same thing as MacBiter (Firefox frequently crashes with a beach ball and needs to be force quit) on my Mavericks laptop. Nytimes.com continues to be one example of a website where it will beachball consistently.

Note that I'm away from home at the moment and I don't have any VMs on my laptop, so I can't test in a clean VM.
