### ISSUE TITLE
Attempting to play Widevine-protected video causes Firefox Dynasty to freeze with a beachball

### ISSUE THREAD

**Issue by Wowfunhappy** [i3roly/firefox-dynasty#16]
On Mavericks, when I go to https://bitmovin.com/demos/drm/ and press play, Firefox freezes with a beach ball and needs to be force quit.

I did not expect Widevine video to actually work (since as far as I know Widevine is officially broken on 10.9). However, it shouldn't freeze the browser!

(This is the first time I've had Firefox freeze on me in more than an hour of browsing!)

**Comment by Wowfunhappy** [comment]
Perhaps unsurprisingly, going into Settings and unchecking "Play DRM-controlled content" fixes the freeze. But ideally this should (eventually) happen automatically, or—failing that—be documented.

**Comment by i3roly** [comment]
are you sure this isn't an artefact from your old FF preferences? DRM should be, and is, enabled by default even when i wipe the profile. though i do think you may be right about the widevine bit.

i will have to find the latest version without getentropy and see if there's an easy way to use that as the fallback. surprised you have it working on that lijnk you gave me. i couldn't get it to play trying a bunch of versions haha

**Comment by Wowfunhappy** [comment]
To be clear, the video at the link does not play no matter what, presumably because Widevine itself is broken on 10.9. That's fine, we can't do much about Google's closed-source DRM nonsense.

> DRM should be, and is, enabled by default even when i wipe the profile.

Yes, by default Widevine is enabled. When Widevine is enabled and I visit the link, Firefox freezes with a beachball and needs to be force quit.

If you manually disable Widevine, the browser doesn't freeze. The video still doesn't play, but this is much better than a freezing browser.

Does this make sense or am I misunderstanding your reply? Sorry if I'm missing something!

**Comment by i3roly** [comment]
it shouldn't freeze, but you should get a notification that the plugin crashed:

https://github.com/user-attachments/assets/073ccab9-785f-45ae-aa7b-a9d96a4b4d04


sounds like mavericks is unsurprisingly throwing a wrench in expected behaviour. i will test it with that as well.

but as it stands, it's possible widevine may work. i saw you guys have a discussion on chromium legacy about this.

**Comment by i3roly** [comment]
hang confirmed on 10.9

**Comment by i3roly** [comment]
i have found a fix and am pushing the commit.

i will update the builds shortly. 

please confirm afterwards. thanks for your DETAILED input.

@macbiter's application has been reconsidered and the order has been reversed, but we caution him with initiating further proceedings without a proper cause of action

order rescinded

**Comment by i3roly** [comment]
it's up @wowfunhappy please report back

**Comment by Wowfunhappy** [comment]
Yep, fixed!

**Comment by i3roly** [comment]
i should note that if you really want some kind of widevine support, you can download this version here:

https://redirector.gvt1.com/edgedl/widevine-cdm/4.10.1582.2-mac-x64.zip

it works on 2 of the 3 modes provided in that link you gave (DASH does not work)

i will ask the team if there’s an easy way to incorporate a fallback for older macs based on a version check in a C++ environment.

as it stands it seems to use pure javascript for the getter and i don’t want to hack at it because this version is too old for DASH on newer macs.

if you *really* want:

it’s also possible there’s a version after 4.10.15xx before 4.10.22xx that works but i can’t find one.
	-just replace the downloaded version in your profile folder, you’ll see the widevine folder and know what to do ;)


Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
I don't really use Widevine (it just seemed like a good thing to test), but @MacBiter may want to try on some real streaming services.

**Comment by i3roly** [comment]
@wowfunhappy you wanna try this build here? it uses VTdecoder by allowing the default settings ont he RDD sandbox.
https://www.icloud.com/iclouddrive/0b7o6sa0-wDesieJmGM33SKRQ#Firefox

i just want to know if it accelerates better than GMP. it may be worth using defaults for RDD's sandbox for <=10.12 systems if AppleVTDecoder works good.

run the executable directly with MOZ_LOG=PlatformDecoderModule:5 as the prefix, and let me know if it says 

using hardware accelerated decoding

**Comment by MacBiter** [comment]
I tried this out, on ITVX which just gave me an error message about browser settings (the usual thing) on the previous settings.

After loading the new Widevine components, I didn't get  the error message and I used ITV search to find a programme to watch. Clicking play I got an endless 'loading' circle, but eventually it played the initial adverts and trailers and sponsor's advert I would expect. Unfortunately after they had finished, instead of the actual programme content I got a black screen and a banner above it saying "Firefox is loading the components needed to play video and audio. Please try again later". When I returned to it, there was the error message. So it was initially successful and then failed sadly . 

Thanks for the effort anyway.

**Comment by MacBiter** [comment]
Yes, that's the version I'm talking about. It partly works in that I get some content (ads, trailers, sponsor), but not the actual programme content.

It's probably that Mavericks breaks Widevine, period, even earlier versions.

**Comment by i3roly** [comment]
it's not mavericks per-se, the problem is google has included new symbols not present in older OSes.

two questions.

1. did you try to load this content without replacing widevine?

2. are you sure you replaced it properly? 

- because it only says it's downloading widevine if it thinks your directory is empty or you don't have it. 

if you did see the plugin crash banner after downloading message, then you need to replace the widevine files and try again.

i suspect all the adverts etc will work because they probably don't have DRM.

**Comment by MacBiter** [comment]
I put the 4 components into the Firefox profile widevine folder, replacing the previous components (the only difference was the 'Licence' which previously was an executable, but the replacement was a text file, so both are in the folder - could that be the problem?). By the way I didn't even get the ads etc before your replacement so there was some success.

**Comment by i3roly** [comment]
ok.

next version to try would be this one: https://redirector.gvt1.com/edgedl/widevine-cdm/4.10.2209.1-mac-x64.zip

but be warned, it may not work at all. if it doesn't, then you're at the mercy of google i guess :/

**Comment by MacBiter** [comment]
I'm at the mercy of google I'm afraid!

Thx for the effort - would Dynasty work ok in High Sierra?

**Comment by i3roly** [comment]
i think it would probably work great and not need anything, but i can't say for sure since i use 10.14

**Comment by MacBiter** [comment]
Ok. I'm going to upgrade  to 10.13 soon, and use a VM for Mavericks. I'll try Dynasty there (currently getting DRM video via 115 ESR but it won't last forever).

**Comment by i3roly** [comment]
on 78 i assume you dont' get DRM, right? 

i wouldn't upgrade unless you feel you absolutely have to.

if you already have a way to get drm video then just stick to that.

i didn't know about google's lockdown on drm through widevine until a day or two ago.

**Comment by MacBiter** [comment]
I can only get DRM via my High Sierra VM (Firefox 115 ESR but also Chrome ESR which is VERY slow!). So instead of Mavericks + 10.13 VM, I might change to 10.13 + Mavericks VM. But as you say, right now I don't have to.

**Comment by Wowfunhappy** [comment]
> the problem is google has included new symbols not present in older OSes.

If it's just down to symbols we/I can (probably) polyfill them (or stub them). Do you know how to view output from Widevine?

**Comment by i3roly** [comment]
test the hardware acceleration thing first lol

yes it’s a symbols thing. your guys’ exchange on the chromium issue is what tipped me off on trying lower versions.

maybe i misinterpreted that git issue though: https://github.com/blueboxd/chromium-legacy/issues/165

i tried the same old 15xx widevine on my 10.14 machine and it behaves the exact same as it does on 10.8

with 22xx, it doesn’t crash but it reports some weird DRM_FAILED_LICENSE_REQUEST which is weird but i think you guys said google purposefully-expires older libraries.

the latest ones (24xx) definitely have getentropy on them, which i think is the reason the plugin loading crashes and was exactly what you guys were talking qabout.

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
> @Wowfunhappy you wanna try this build here? it uses VTdecoder by allowing the default settings ont he RDD sandbox.

I browsed casually for about 5 minutes, and visited websites including nytimes.com. It didn't freeze/beachball once. I'd really like to test for longer to confirm stability, but for the moment it seems to be working okay.

Terminal output attached. There's a lot of it!

[Terminal Saved Output.txt](https://github.com/user-attachments/files/17387778/Terminal.Saved.Output.txt)

**Comment by Wowfunhappy** [comment]
> but i think you guys said google purposefully-expires older libraries.

That's my understanding, yes.

> the latest ones (24xx) definitely have getentropy on them, which i think is the reason the plugin loading crashes and was exactly what you guys were talking qabout.

It can't _just_ be getentropy though, or it the latest version of Widevine would work in Chromium Legacy. As you can see in the discussion, Chromium Legacy polyfills getentropy. Those polyfills were sufficient to make Widevine work a year ago, but not anymore, so presumably something else is needed in the latest version.

Complicating things is that the way Chromium Legacy does the polyfill was never open sourced (blueboxd said "the code is currently entangled"). My normal method for polyfilling won't work because I can't modify the widevine binary without breaking the checksum. I could modify libSystem.B.dylib itself but I'd really rather not for obvious reasons.

**Comment by i3roly** [comment]
> > @Wowfunhappy you wanna try this build here? it uses VTdecoder by allowing the default settings ont he RDD sandbox.
> 
> I browsed casually for about 5 minutes, and visited websites including nytimes.com. It didn't freeze/beachball once. I'd really like to test for longer to confirm stability, but for the moment it seems to be working okay.
> 
> Terminal output attached. There's a lot of it!
> 
> [Terminal Saved Output.txt](https://github.com/user-attachments/files/17387778/Terminal.Saved.Output.txt)

that looks good. it's using hardware decoding and i'm not sure the main release with GMP does that, which is why i insisted you give it a run.

keep testing and keep me posted

**Comment by i3roly** [comment]
> > but i think you guys said google purposefully-expires older libraries.
> 
> That's my understanding, yes.
> 
> > the latest ones (24xx) definitely have getentropy on them, which i think is the reason the plugin loading crashes and was exactly what you guys were talking qabout.
> 
> It can't _just_ be getentropy though, or it the latest version of Widevine would work in Chromium Legacy. As you can see in the discussion, Chromium Legacy polyfills getentropy. Those polyfills were sufficient to make Widevine work a year ago, but not anymore, so presumably something else is needed in the latest version.
> 
> Complicating things is that the way Chromium Legacy does the polyfill was never open sourced (blueboxd said "the code is currently entangled"). My normal method for polyfilling won't work because I can't modify the widevine binary without breaking the checksum. I could modify libSystem.B.dylib itself but I'd really rather not for obvious reasons.

i see.

what i do know is, for example:
4.10.2209 doesn't crash but it gives me DRM_FAILED_LICENSE_REQUEST
4.10.2391 and up CRASH, and all of them have getentropy

i don't know how chromium works. all i know is that firefox is not entangled with widevine. it loads it as a separate library. if the system has all the symbols used by the library, we wouldn't see that crash banner.

it's possible you can trick firefox to loading one of your wild concoctions by simply naming them appropriately. it doesn't seem to care. or so i think it doesn't. 

the symbols need to get resolved before the newer libraries will load, and only then can we see if it will work.

**Comment by Wowfunhappy** [comment]
@i3roly For a normal app, this would be extremely easy. I would just apply the process I outlined years ago for Unity games: https://apple.stackexchange.com/questions/414688/how-can-i-run-newer-unity-games-on-os-x-10-9-mavericks/414689

Unfortunately, Widevine is not a normal app, because the binary is (presumably) checksummed. That means I need to polyfill this symbol _without_ modifying the binary in any way. I can think of two ways to do this:

1. Run Widevine with a flat namespace and then use DYLD_INSERT_LIBRARIES to inject my polyfill. This assumes Widevine will work with a flat namespace, which it probably will because @krackers says Chromium Legacy runs Widevine that way. Unfortunately, Firefox will definitely not work with a flat namespace (starting the Firefox binary with `DYLD_FORCE_FLAT_NAMESPACE=1` leads to a segmentation fault), so I need to somehow start Widevine with a flat namespace but not Firefox. I don't know how to do that. Bluebox apparently does but the method is not open source.
2. Replace `libSystem.B.dylib` on disk with my own library that polyfills the symbol and then re-exports the original library. This is very scary but I guess it's what disposable virtual machines are for. Note, however, that we could _never_ ship this to users, it would only be for experimentation.

I can (probably) try option 2 this weekend. But first, I really need a way to get crash logs from Widevine, or I won't know if the polyfill is working. I mean, I suppose if Widevine videos suddenly start playing I would know that it worked, but I think it's more likely that there is more than one symbol that has to be polyfilled, particularly because (aiui) Chromium Legacy already polyfills this, and while that used to work it doesn't any more.

**Comment by Wowfunhappy** [comment]
@krackers So that's something @i3roly would have to put into Firefox Dynasty so the environment variable gets hooked when Widevine launches, right? There's no easy way I can play around with it on my end (unless I actually get Firefox building locally).
