### ISSUE TITLE
The window control ("traffic light") buttons should not appear in full screen on 10.7–10.9

### ISSUE THREAD

**Issue by Wowfunhappy** [i3roly/firefox-dynasty#17]
I know this is a trivial issue, but I think it's trivially fixable!

In OS X 10.9, if you full screen basically any app—Finder, QuickTime Player, Mail, Calendar—the window control ("traffic light") buttons disappear. You have to exit full screen to see them again. I'm mostly undecided as to whether this was a good design decision, but consistency is nice.

In Firefox Dynasty, the window control buttons still appear in full screen mode.

However, the buttons go away if you set `browser.theme.macos.native-theme` to `false` in about:config. So far, I haven't noticed any other side effects from this setting. Maybe this could be done automatically for users on 10.9 and below?

**Comment by i3roly** [comment]
i don't see these buttons though, am i doing it wrong?:


https://github.com/user-attachments/assets/c0567cc3-effc-46cf-b5e6-01d6370eaefb

**Comment by Wowfunhappy** [comment]
...and now I can't see them either, even after unsetting the preference and clearing all preferences! I swear they were there last night, I switched the config back and forth and watched them disappear and reappear!

Sorry! I will re-open this if I can figure out how to make the buttons come back in full screen...
