### ISSUE TITLE
Pop Out Video → Full Screen → Exit Full Screen (via OS X menu bar) leads to invisible video.

### ISSUE THREAD

**Issue by Wowfunhappy** [i3roly/firefox-dynasty#18]
To reproduce:

1. Open a Youtube video (or likely almost any video), such as https://www.youtube.com/watch?v=WO2b03Zdu4Q
2. Click the "pop out video" icon.
3. Click the Fullscreen icon in the bottom right corner.
4. Exit full Screen by:
     1. Hovering your mouse at the top of your monitor to unhide the OS X menu bar, then clicking the icon in the top right corner to exit full screen.
     2. Pressing the `esc` key.
     * Do _not_ click Firefox's "exit full screen" button in the bottom right corner, which won't trigger the bug.

The video will disappear. The tab will say "the video is playing in Picture-in-Picture" mode, and sound will be audible, but there's no window to be seen.

Additionally, if you follow steps 1–3, then switch back to the space which contains your Firefox window while the PiP video is still full screen, the PiP will display over the Firefox window and everything else. I'm not actually sure what the expected behavior is here—I'd hope it's just "let the video keep playing in its own full screen space and don't interfere with other spaces" except Mozilla and I don't always agree—but it clearly shouldn't do _this_.

You can "fix" these problems by setting `full-screen-api.macos-native-full-screen` to `false` in about:config. However, you loose some potentially nice OS X integration in the process.

Tested on 10.9.5. I'm on my main system rather than a VM, but I can test in a clean VM if you really think it's system specific.

**Comment by i3roly** [comment]
i know this is fixed in the latest central.

seems it uses spaces implicitly on older macs


https://github.com/user-attachments/assets/3406c54a-491b-4049-9587-338c6a7ff37b

**Comment by RJVB** [comment]
> seems it uses spaces implicitly on older macs

You mean newer OS versions no longer have that extremely annoying obligatory feature where your other displays will go black if you fullscreen an app on one display with "displays have separate spaces" *not* set?

**Comment by Wowfunhappy** [comment]
@i3roly In your video, make sure to exit fullscreen via macOS's icon, not Firefox's. Hovering your mouse at the top of your (virtual) monitor to unhide the OS X menu bar, then click the icon in the top right corner.

**Comment by i3roly** [comment]
i pressed the escape key in one of them, and the 'x' button on the other. so the escape key worked. 
and i just did what you asked and it works evne better than using the 'esc' key or clicking the x button (two versions i showed in the previous video):




https://github.com/user-attachments/assets/6b4750f1-e370-4736-a268-d8c3d3c39c00

**Comment by Wowfunhappy** [comment]
Huh, yes it did work there! I'm using the test build for #26 from a few days ago which I thought was based on central. Odd, I did try this in a clean VM...

**Comment by Wowfunhappy** [comment]
Okay, this is actually a difference between 10.8 and 10.9. (It looks like you were testing in 10.8 from your video).

Only 10.9 has the bug when you exit fullscreen via the OS X icon. 10.8 works fine.

Both 10.8 and 10.9 do have the secondary oddity where if you fullscreen the PiP window, then switch back to your main space, the PiP window will appear in front of everything. As I said, I don't actually know for sure what the expected behavior is here, but I really hope it's not this!!!

I tested https://github.com/i3roly/firefox-dynasty/releases/tag/fuckaround in 10.8 and 10.9 VMs open side by side.

**Comment by i3roly** [comment]
i don't even know how well spaces are supported in VMs, but maybe it's totally native. i'm not sure.

personally i won't be fixing this because i don't care about it.

sorry

**Comment by Wowfunhappy** [comment]
Fair enough!
