### ISSUE TITLE
[OS X 10.9] dyld: Symbol not found: _pthread_chdir_np

### ISSUE THREAD

**Issue by RJVB** [i3roly/firefox-dynasty#20]
FF Dynasty 132.0 seemed to work fine for me in quick testing, so I set it up to run on a clone of the profile I use in Waterfox (G3.2.7-osxfix-eol).

It starts up OK, opening all the windows it should that even look like they do in Waterfox, but then it hangs after I've just been able to cancel the "make default browser" invitation. Launching from a terminal I see

```
> /path/to/FFDynasty-1320/Firefox.app/Contents/MacOS/firefox
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2024-10-28 00:02:51.466 firefox[11376:10d03] CoreText performance note: Client called CTFontCreateWithName() using name "Lucida Grande" and got font with PostScript name "LucidaGrande". For best performance, only use PostScript names when calling this API.
2024-10-28 00:02:51.467 firefox[11376:10d03] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
[GFX1]: NextSurface returning false because of invalid mSize (0, 0).
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
console.error: "attribute_timeout: attachedFxAOAuthClients"
console.error: (new Error("attachedFxAOAuthClients targeting getter timed out after 5000ms", "resource://messaging-system/targeting/Targeting.sys.mjs", 139))
JavaScript warning: moz-extension://a4d71339-e05c-a94f-84ab-921ad5ea5077/js/Driver/Bookmarks.js, line 1642: unreachable code after return statement
dyld: lazy symbol binding failed: Symbol not found: _pthread_chdir_np
  Referenced from: /path/to/FFDynasty-1320/Firefox.app/Contents/MacOS/XUL
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_chdir_np
  Referenced from: /path/to/FFDynasty-1320/Firefox.app/Contents/MacOS/XUL
  Expected in: /usr/lib/libSystem.B.dylib

_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
```

It seems quite likely that the attempted use of `pthread_chdir_np()` is the culprit here; they appear just before the beachball A bit strange that FF wouldn't be prepared to handle XUL crashes though...

**Comment by RJVB** [comment]
FWIW, re: `pthread_[f]chdir_np()`:

the [Chromium source indicates that this concept exists since 10.5, but you have to use the syscall directly](https://stackoverflow.com/a/55428238/1460868).

**Comment by RJVB** [comment]
It looks like the issue can be triggered by installing the "Video DownloadHelper" extension in a fresh profile:

https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/

**Comment by Wowfunhappy** [comment]
> It looks like the issue can be triggered by installing the "Video DownloadHelper" extension in a fresh profile:

Do I need to do anything with the addon once installed? I installed it but my Firefox is still working.

**Comment by RJVB** [comment]
>Do I need to do anything with the addon once installed? I installed it but my Firefox is still working.

I didn't have to do anything, I just started with a new profile and only added the extension. What OS version did you try this on?
The extension does have a helper application which I should have installed; I could try to move the copy out of the way and reinstall the extension to see if that makes a difference.

The pthread_chdir_np function is available "as is" from 10.12 upwards.

Anyway this is an extension I use and IMHO it's not an issue in that extension but in the XUL library which can call a function that doesn't exist. If the extension can trigger that call (a priori via javascript) then a site could do it too and since the functionality is available via a syscall I would argue that there is no excuse not to fix that.

FWIW: I have a simple wrapper around the `dlsym(2)` function and if I use that to load the XUL library (with `DYLD_LIBRARY_PATH` set to `/path/to/XUL`) I get an error about another missing function (in the `clock_gettime` family).
https://github.com/RJVB/legacy-tools/blob/master/dlsym.c

**Comment by Wowfunhappy** [comment]
> I didn't have to do anything, I just started with a new profile and only added the extension. What OS version did you try this on?

10.9. It looks like the helper application needs Mojave, do you have an older version?

> If the extension can trigger that call (a priori via javascript) then a site could do it too and since the functionality is available via a syscall I would argue that there is no excuse not to fix that.

I completely agree, I was just stating that I can't personally trigger it in the way you suggested.

> I get an error about another missing function (in the `clock_gettime` family).

That should be trivially fixable with MacPorts Legacy Support, right?

**Comment by RJVB** [comment]
>10.9. It looks like the helper application needs Mojave, do you have an older version?

Yes, I built a version myself, apparently long ago already. So I cannot exclude that the issue at hand is triggered by having an outdated version installed, but I can confirm that putting the helper app in the Trash helps prevent the issue. Putting it back will then trigger the issue as soon as the extension checks for it.

I actually tested this in a profile that I had created to see if I could trigger the issue by connecting to my FF profile and fetching my settings, bookmarks etc. I had disabled the Video DownloadHelper addon which had apparently blocked syncing; it resumed as soon as I re-enabled the addon. 

It really seems to be only Video DownloadHelper that currently exposes the unresolvable symbol, but:

>I completely agree, I was just stating that I can't personally trigger it in the way you suggested.

So the observation above suggests that it's indeed the extension that tries to do a thread-specific chdir (or that attempts an operation for which FF will use pthread_chdir_np) - possibly a chdir into the helper app's directory. That confirms my hunch that other extensions or sites might do this too.

>> I get an error about another missing function (in the `clock_gettime` family).
>That should be trivially fixable with MacPorts Legacy Support, right?

```
> env DYLD_LIBRARY_PATH=./FFDynasty-1320/Firefox.app/Contents/MacOS dlsym ./FFDynasty-1320/Firefox.app/Contents/MacOS/XUL
dlsym: can't open ./FFDynasty-1320/Firefox.app/Contents/MacOS/XUL (dlopen(./FFDynasty-1320/Firefox.app/Contents/MacOS/XUL, 6): Symbol not found: _clock_gettime_nsec_np
  Referenced from: ./FFDynasty-1320/Firefox.app/Contents/MacOS/XUL
  Expected in: /usr/lib/libSystem.B.dylib
 in ./FFDynasty-1320/Firefox.app/Contents/MacOS/XUL)
Exit 1
```

Sadly the function in question is not in Legacy-Support (but judging from the name it should be simple enough to emulate).

It's a pity that I no of no way to get the full list of unresolvable symbols; who knows how many more there are!

**Comment by RJVB** [comment]
In `ipc/chromium/src/base/process_util_mac.mm:26` :

```
extern "C" {
// N.B. the syscalls are available back to 10.5, but the C wrappers
// only in 10.12.  Fortunately, 10.15 is our current baseline.
int pthread_chdir_np(const char* dir) API_AVAILABLE(macosx(10.12));
int pthread_fchdir_np(int fd) API_AVAILABLE(macosx(10.12));
```
And from `syscall.h`:
```
#define   SYS___pthread_chdir 348
#define   SYS___pthread_fchdir 349
```

The (missing) C calls are just wrappers; it should be possible to replace the declarations at line 26 with actual definitions:
```
int pthread_chdir_np(const char* dir)
{
    return syscall(SYS___pthread_chdir, dir);
}

int pthread_fchdir_np(int fd)
{
    return syscall(SYS___pthread_fchdir, fd);
}
```
Patch: 
[pthread_chdir.diff](https://github.com/user-attachments/files/17575096/pthread_chdir.diff.txt)


While we're at it:
`third_party/rust/zeitstempel/src/mac.rs:31`:
```
extern "C" {
    fn clock_gettime_nsec_np(clock_id: clockid_t) -> u64;
}
```

`mozglue/misc/Uptime.cpp:77`:
```
Maybe<uint64_t> NowExcludingSuspendMs() {
#if !defined(MAC_OS_VERSION_10_12) || MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_VERSION_10_12
  struct timespec ts = {0};
  return Some(clock_gettime_missing(CLOCK_UPTIME_RAW, &ts)/ kNSperMS);
#else
  return Some(clock_gettime_nsec_np(CLOCK_UPTIME_RAW) / kNSperMS);
#endif
}

Maybe<uint64_t> NowIncludingSuspendMs() {
#if !defined(MAC_OS_VERSION_10_12) || MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_VERSION_10_12
  struct timespec ts = {0};
  return Some(clock_gettime_missing(CLOCK_MONOTONIC_RAW, &ts)/ kNSperMS);
#else 
  return Some(clock_gettime_nsec_np(CLOCK_MONOTONIC_RAW) / kNSperMS);
#endif
}  
```

`mozglue/misc/AwakeTimeStamp.cpp:115`:
```
AwakeTimeStamp AwakeTimeStamp::Now() {
#if !defined(MAC_OS_VERSION_10_12) || MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_VERSION_10_12
    struct timespec tv;
    return AwakeTimeStamp(clock_gettime_missing(CLOCK_UPTIME_RAW, &tv)/ kNSperUS);
#else
    return AwakeTimeStamp(clock_gettime_nsec_np(CLOCK_UPTIME_RAW) / kNSperUS);
#endif 
} 
AwakeTimeStamp AwakeTimeStamp::NowLoRes() { return Now(); }
```

The reference to `clock_gettime_nsec_np` must come from the Rust file which has what seems to be a runtime detection of its availability. The two C++ files should build in a call to replacement functionality.

**Comment by RJVB** [comment]
Hoping the attached patch will help speed up fixing this issue!

**Comment by Wowfunhappy** [comment]
> How about you write a dynasty-updating prefpane (I presume there's no updating functionality in FF Dynasty anyways)? ;)

I am planning on it, but it might take a while. I want to start on a stronger foundation this time so the codebase doesn't get out of control. I also have quite a few tweaks I want to apply on top, such as [this code](https://gist.github.com/Wowfunhappy/b09900c5420767651338a57692348e31) for fixing key equivalents. I'm working on extending that to add additional items to the menu such as "reload page", and then I want to make use of Firefox's theming support to make this look like a proper Aqua app.

**Comment by RJVB** [comment]
Sounds good, but you want to use Firefox for the looks of what exactly?

**Comment by Wowfunhappy** [comment]
Oops, I want to make _Firefox_ look like a proper Aqua app. The toolbar should have the correct gradient and so on.

**Comment by RJVB** [comment]
>Oops, I want to make _Firefox_ look like a proper Aqua app. The toolbar should have the correct gradient and so on.

Well, as long as you do that with regular themes you're welcome to :) I don't miss that gradient but rather appreciate how the combined title+tab bar and just the address bar are about as compact as can be.

**Comment by RJVB** [comment]
Be that all as it may, it's not what this ticket is about!


How *does* one get @i3roly to at least acknowledge an issue?

**Comment by i3roly** [comment]
you may be right about the pthread thing, but you're wrong about the clock_gettime_np part.  i know this because i have tested it on older OSes that don't have the symbol, and it was an early observation.

i have notifications turned off on this repository for good reason, like a half-correct criticism which would otherwise irritate me and cause me to say rude things.

**Comment by RJVB** [comment]
On Thursday November 07 2024 18:10:33 gagan sidhu wrote:
>
>you may be right about the pthread thing, 

I don't think the OS would lie about the pthread symbol, and if I were to guess it'd be that my patch more or less reverts a change upstream made since they upped the minimum requirement to 10.15 

>but you&#39;re wrong about the clock_gettime_np part.  i know this because i have tested it on older OSes that don&#39;t have the symbol, and it was an early observation.

You'll have noticed that I don't claim that it's an absolute requirement. But who can guarantee that its use in the rust code won't ever get invoked through an otherwise innocent-looking extension, just like pthread_chdir_np? Plus, the fallback implementations in the other places may also be removed without much warning.

>like a half-correct criticism

I wasn't, but who's criticising now? O:^)

**Comment by i3roly** [comment]
it will not get invoked by the piece of code you're referencing.

it's the same idea behind getentropy in libc. the declaration isn't what will trigger the symbol exception, but rather the actual call. i dealt with this quite a bit early on.

anyways, most people don't want my attention. you're the first that has screamed for it, and now that you have it: what exactly are your demands here? i  tried your pthread suggestion and it does not work. 

i want to note two things:
1. chromium said it "exists in concept", but having tried it, it doesn't seem to be "drop in"
2. as @wowfunhappy and @krackers can attest, especially for APPUL: 
> availability does not imply stability. 

we learned this when i thought the availability of pthread firstfit mutexes in <10.14 systems was a good idea, causing everyone grief until i removed them completely.

**Comment by RJVB** [comment]
Now that I figured out how to manhandle mozilla's repository, here's the commit that introduced use of the function(s): https://searchfox.org/mozilla-central/diff/996eb87d1d8b942dac44d7582aa2b5c66194c351/ipc/chromium/src/base/process_util_mac.mm#26 . Later code only uses `pthread_fchdir_np`, FWIW.

> it will not get invoked by the piece of code you're referencing.

I'm guess that "it" is the clock_gettime function? I'll take your word for it. Let's focus on the pthread thing which is a blocker for me moving to using FF Dynasty as my main browser.

> the declaration isn't what will trigger the symbol exception, but rather the actual call. i dealt with this quite a bit early on.

Of course, thanks to Apple's weak linking trick. Without that `@available()` wouldn't work...

> anyways, most people don't want my attention

I guess they don't file bug reports then...

> what exactly are your demands here? i tried your pthread suggestion and it does not work.

I'd like some kind of fix that will stop Firefox from freezing because some subprocess gets killed when it tries to use an unavailable symbol.

> > availability does not imply stability.

What I can do is see if the wrapper implementation I proposed in my patch works for me in a simple test application, but maybe you have already done that yourself?

Github doesn't send email notifications for edits to posts in the issue tracker so it's only now that I saw the error message that my patch supposedly gives. Is that text printed by FF itself?
```
Error: Platform version '132.0.2' is not compatible with
minVersion >= 132.0
maxVersion <= 132.0
Maybe try to reinstall Firefox?
```

Do you see any logical relation to my proposed change? My patch doesn't do anything to the browser version, as seems to have happened here. That a `132.0 <= $version <= 132.0` will fail when `version=132.0.2` is obvious but how could that be related to my patch?

What OS version did you test on? One < 10.12? And your build system?

Here's an older version of very similar Chromium code (the relevant code in XUL also seems to be taken from Chromium):
https://chromium.googlesource.com/chromium/src/+/6eb6d90fa2ce1ff368e7d0088c734a7bc1c8eabd/base/process/launch_mac.cc#96

Let me try to make a new patch based on this approach without downloading the whole behemoth again. If by chance the above error happened on 10.12 or later there is the remote possibility that something in Apple's SIP-and-whatever didn't like the overloading of a system function.

**Comment by i3roly** [comment]
are you stupid?

do you think i pushed this stuff without testing? can you read?

my goodness gracious. no wonder you get dunked on by the macports-dev people.

i fucking tested it on 10.8. have you even read other tickets? you're banned. fuck off.
