### ISSUE TITLE
134.0b7 freezes "after a while"

### ISSUE THREAD

**Issue by RJVB** [i3roly/firefox-dynasty#25]
For now just a heads-up and a bummer: when running my usual session v134.0b7 freezes after a while, at least when I leave it idle.
There's no output on the terminal whatsoever and I haven't found in the system.log either yet, but I also have no idea exactly when the hang occurs because the 3 times it happened now I wasn't using the browser.

Session is 5 windows, 26 tabs total, but all but 2 are suspended via the FF build of The Great Suspender extension. The open tabs have the whatsapp web interface plus and the instagram DM page open; both have serviceworkers AFAIK.

I'd been running 132.0 from Oct. 27th (relinked with the MacPorts LegacySupport library for the `pthread_chdir` functions) and that one was rock stable for me. Now back down to 132.0.3 for my main profile, crossing fingers it's going to be as stable.

**Comment by i3roly** [comment]
it's beta so it could be anything.

maybe it's the plugin or something. no idea.

**Comment by RJVB** [comment]
Of course, sadly. For now this is just a flag that something ain't completely right but it's going to need the right amount of serendipity to figure out what ;)

My experience on Linux is that the FF beta is that it's perfectly reliable as a daily driver.

**Comment by RJVB** [comment]
Update: annoyingly it looks like it's web.whatsapp.com rather than instagram.

I've been running a newly created profile that syncs with my firefox profile and it's logging into whatsapp that freezes the app after an as yet undetermined amount of time.

One difference with v132 is this new terminal output when (re)loading the web.whatsapp.com page (even when not logged in):

```
JavaScript warning: https://static.whatsapp.net/rsrc.php/v4/yY/r/bEQhmmkuqVO.js, line 115: unreachable code after return statement
JavaScript warning: https://static.whatsapp.net/rsrc.php/v4iWBv4/y7/l/rt/vVgpke309DiL4eWZY1dwH02RSfFSjWLjPGyeTeqrB8ZU_2SsOE-ssqJNxZA4A3xztGvsWqehdEtWw.js, line 16: unreachable code after return statement
JavaScript warning: https://static.whatsapp.net/rsrc.php/v4iWBv4/y7/l/rt/vVgpke309DiL4eWZY1dwH02RSfFSjWLjPGyeTeqrB8ZU_2SsOE-ssqJNxZA4A3xztGvsWqehdEtWw.js, line 16: unreachable code after return statement
JavaScript warning: https://static.whatsapp.net/rsrc.php/v4iWBv4/y7/l/rt/vVgpke309DiL4eWZY1dwH02RSfFSjWLjPGyeTeqrB8ZU_2SsOE-ssqJNxZA4A3xztGvsWqehdEtWw.js, line 16: unreachable code after return statement
JavaScript warning: https://static.whatsapp.net/rsrc.php/v4iWBv4/y7/l/rt/vVgpke309DiL4eWZY1dwH02RSfFSjWLjPGyeTeqrB8ZU_2SsOE-ssqJNxZA4A3xztGvsWqehdEtWw.js, line 127: unreachable code after return statement
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
JavaScript warning: https://static.whatsapp.net/rsrc.php/v4iTVX4/yG/l/rt/MtciTMo1kZQ.js, line 740: unreachable code after return statement
```

**Comment by i3roly** [comment]
those errors aren't fatal though

**Comment by RJVB** [comment]
On Tuesday December 10 2024 13:29:02 gagan sidhu wrote:
>those errors aren't fatal though

Indeed, or at least they shouldn't be, plus I haven't seen the TamperMonkey errors anymore. Maybe they got through after I killed the process with a SIGINT.
I keep checking off boxes, and will also see if the freeze occurs with a fresh browser profile.

**Comment by RJVB** [comment]
This one remains illusive. I could reproduce the freeze in a fresh test profile that syncs with my main FF profile, even in a private window. And then I couldn't anymore, and AFAIK all I did was disconnect the sync feature so I could start disabling add-ons. Reconnecting did NOT reintroduce the freeze.

So now I'm using another test profile that's never been connected to my main profile and it does freeze even in safe mode.

Is there a token I can set MOZ_LOG to so all logging options are activated? "all" doesn't seem to have that effect and the online doc is of little help.

**Comment by i3roly** [comment]
if you’re still using 134b07 then i think it’s probably related to my unorthodox way of enablign unsafe plugins.

i would rather you try 13303 and see if you can reproduce it there, since 13303 is stable and should support your illegal plugins

**Comment by RJVB** [comment]
I just made a few changes to that freezing profile which seems to have solved the issue - still in "safe" mode. Lemme try to recall exactly what and revert them, starting with letting FF be clever with secure DNS.

I'm not using any illegal plugins O:^) , the only unsanctioned one I'm running is an unsigned version of the suspender addon that was changed only so it doesn't call a non-existent JS function.
I'll keep your suggestion in mind, but is your "unorthodox way of enabling" something that can have side-effects at runtime (beyond deciding whether or not to enable any given extension), in particular in safe mode when addons aren't loaded at all?

**Comment by i3roly** [comment]
yes, it may have, because it was using a combination of settings from the release and beta (only on beta) to produce the desired effect (allowing illegal plugins).

after further testing i found wowfunhappy’s recommendation of the single flag did work, but you have to rebuild the entire tree for it to propagate properly. this is the approach taken in 13303

Thanks,
Gagan

**Comment by RJVB** [comment]
Understood.

I still think it's preferable to figure out first exactly what allows to avoid the freeze in 134.0b. After all there's bound to be a lot else that differs between 133 and 134 .

AFAICT right now it's not the disabling of secure DNS, but I may need to create an entirely new test profile to be sure of that. At this point I'm not even excluding the possibility that you can't turn the freeze back on once you managed to get rid of it...

**Comment by i3roly** [comment]
it’s called beta for a reason. i wouldn’t worry too much about it.

**Comment by RJVB** [comment]
>it’s called beta for a reason. i wouldn’t worry too much about it.

True, but I've been running it for years on Linux without any issues like this, and if the freeze is the result some new feature that makes it into a release version then I do have a problem. I have a desktop whatsapp session open most of the time and would prefer not to have to run it in an older version of the browser. I'd use Ferdium if someone cared to backport the Chromium framework and Electron.app, but I don't see that happening in this lifetime ;)

**Comment by RJVB** [comment]
Closing this as I am no longer able to reproduce it, not even with my main profile. Thanks for the suggestions but I guess it'll remain a mystery what went wrong.

**Comment by RJVB** [comment]
Well, great. The freezing is back, but only in my main profile.

Good idea to try 133.0.3 though: it doesn't seem to be affected. If possible, please build the next 134 beta release with those same settings for not requiring signed extensions so that we can test if that's indeed the culprit here. It still seems farfetched to me but the code base must be a complex enough ensemble that even moving a semicolon can have unexpected effects ;)

Happy holidays...!
