### ISSUE TITLE
Widevine upgrade needs to be incorporated

### ISSUE THREAD

**Issue by MacBiter** [i3roly/firefox-dynasty#8]
This is an issue with all legacy browsers - streaming DRM video that uses Widevine stopped working yesterday, 6th September. 

There is one weird thing that's only to do with Firefox-dynasty - BBC iPlayer (which doesn't use Widevine) also doesn't stream video, which it still does in - for example - Chromium Legacy. However, I've been using iPlayer in Chromium for a couple of years, so its non-functioning in Firefox-dynasty, which I only found out today, may not have happened yesterday and may not be anything to do with the Widevine issue. It does need looking at though.

**Comment by i3roly** [comment]
incorrect understanding of Firefox. 

already using a recent widevine. look in ~/Library/Application Support/Firefox/Profiles/<profile name>/ and see for yourself. 

there is a widevine folder there because it's downloaded on demand and NOT bundled with the app.
