### ISSUE TITLE
Attempting to share your screen causes Firefox to freeze on OS X 10.9 Mavericks.

### ISSUE THREAD

**Issue by Wowfunhappy** [i3roly/firefox-dynasty#9]
On Mavericks, go to https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing, click "Share Your Screen", and select a window.

The browser will freeze and will have to force quit.

I am running OS X 10.9.5 (13F1911) with an nVidia GTX 780 Ti.

**Comment by i3roly** [comment]
hey man thanks for bringing this to my attention. the 131 build i just uploaded did not see this in time, but i'm uploading a new one in just a second that fixes this.

it was a stupid exception raised by the lack of the button selector on the nsstatusitem class

**Comment by Wowfunhappy** [comment]
Yep, fixed, thank you!

**Comment by Wowfunhappy** [comment]
Hmm, something still isn't quite working.

Invariably, within 30 seconds of starting the sharing, the page freezes. I can still scroll but cannot click links or highlight text. I can usually close the tab, but the sharing indicator window will remain. Firefox usually beach-balls shortly afterwards.

**Comment by i3roly** [comment]
might be something on your end or you may have to do more testing.

i let it run for a bit and it seemed fine.

https://github.com/user-attachments/assets/abe16a47-d251-4843-a668-519a97ca9a05

**Comment by Wowfunhappy** [comment]
Can you try opening a new tab and then switching back to the screen sharing tab? This isn't super consistent but seems to help make the freeze appear.

**Comment by i3roly** [comment]
it’s not that.

it’s related to sandboxing. i spent all afternoon trying to figure out what exactly is causing the problem, but the issue is with ‘encrypted videos’.

the videos you’re trying to watch (nytimes, @macbiter’s liverpool fc) are “AES-encrypted” videos.

there was an issue with the firefox sandbox and playing these videos, but this change won’t work for older macs since they don’t have the xpc-service flag.

https://hg.mozilla.org/releases/mozilla-beta/rev/7b0b48569ec8

if either of you try to bing aes encrypted videos and find one to play, you will see it doesn’t work.

this is the root of, and the sole, problem. when i used a broken sandbox (testing variables, it breaks completely if you don’t have the syntax right), i would get it buffering and the decoder wouldn’t error out, but it still didn’t play.

it’s a matter of finding out how to get the sandbox on pre 10.10 systems (i think this stuff works on 10.10, at least) to allow encrypted video content

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
I'm going to close this because, although the page still doesn't work for me, I don't think the freeze is related to screensharing. I'm getting these hard freezes on _lots_ of pages!

**Comment by i3roly** [comment]
i am too on the latest build, but the alternative is to put back urandom and let the other videos not play.

it’s an RDD sandboxing issue, and it’s tragic there doesn’t seem to be a simple fix.

the urandom trick definitely worked last week. i tried it extensively before posting.

but it seems i was just super lucky during that test period

Thanks,
Gagan

**Comment by i3roly** [comment]
if you run the firefox executable directly from the MacOS directory like this:

MOZ_DISABLE_RDD_SANDBOX=1 ./firefox

everything should work. the problem is the decoder for more sophisticated video/audio types isn’t being ‘let through’

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
> MOZ_DISABLE_RDD_SANDBOX=1 ./firefox

Yes! It's still not entirely stable for me (I hit a hard freeze two times in ~10 minutes of testing) but it made a huge difference!

**Comment by i3roly** [comment]
you can try with all of them disabled if you want

 MOZ_DISABLE_CONTENT_SANDBOX=1 MOZ_DISABLE_GMP_SANDBOX=1 MOZ_DISABLE_RDD_SANDBOX=1 MOZ_DISABLE_SOCKET_PROCESS_SANDBOX=1

my own suspicion is that it’s most RDD sandbox though

could be process or utility sandbox as well, but RDD sandbox primarily

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
Yes, that seems to have gotten rid of all the beach balls! It _is_ causing me to run into a different issue where the browser will become unable to load any new content (any new pages you navigate to won't render until you restart the browser), but it doesn't hard freeze.

**Comment by i3roly** [comment]
you can also run the program like normal and set the preference “media.utility-applemedia.enabled” to false andthat should also work.

not sure about the content clog after a while though

this is so fucked. why can’t the apple media decoder get through the sandbox on older macs. just absolutely weird

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
> you can also run the program like normal and set the preference “media.utility-applemedia.enabled” to false andthat should also work

That actually doesn't seem to work for me. If can do that and launch Firefox without those command line args I get the beachball.

**Comment by i3roly** [comment]
sorry it’s media.rdd-applemedia.enabled not utility

sorry

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
I actually tried with both and got the beach ball!

I think the "content clog" (I like that name!) may be related to https://github.com/i3roly/firefox-dynasty/issues/15. When it happens, I can see the Firefox process using 100% CPU. Unlike when  WebExtensions gets stuck on 100% CPU, profiling the process doesn't work, but it would make sense that both can't garbage collect properly or something.

**Comment by i3roly** [comment]
it’s possible there is a garbage collection issue for older systems, yes.

but the applemedia rdd flag should work.

if the rdd sandbox is disabled and it works, then so should the applemedia rdd flag.

there is no reason for one to work and not the other, as the rdd sandbox being disabled lets the apple media decoder through.

it’s also possible there are hanging processes from older sessions, too. earlier today when i was testing i had a ton of plugin-containers and firefox sandbox content zombie processes i had to clean up.

fwiw when i test in 10.7 and i get a crash report, it does say gc is off. i thought this was the desired behaviour by mozilla:

Application Specific Information:
objc[2438]: garbage collection is OFF

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
> fwiw when i test in 10.7 and i get a crash report, it does say gc is off. i thought this was the desired behaviour by mozilla:

I always thought that referred to OS X's garbage collection? Like the thing that was deprecated in favor of Automatic Reference Counting, and removed entirely at some point (IIRC it was 10.11 but don't quote me on that).

I think the GC being referred to in the Firefox profile is for Javascript. So like the Javascript interpreter can't garbage collect.

> there is no reason for one to work and not the other, as the rdd sandbox being disabled lets the apple media decoder through.

Well I had to run with all the sandboxes turned off, not just rdd.

> it’s also possible there are hanging processes from older sessions, too. earlier today when i was testing i had a ton of plugin-containers and firefox sandbox content zombie processes i had to clean up.

I thought I closed those manually but let me try with a full reboot...

**Comment by i3roly** [comment]
i think earlier you said just

> MOZ_DISABLE_RDD_SANDBOX=1 ./firefox

worked but it caused some kind of hang after using it for a while

it’s possible that the garbage collection issue you’re experiencing with all sandboxes disabled is possibly ‘expected’. i’m not sure


Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
> worked but it caused some kind of hang after using it for a while

Oh, yes, I actually forgot—with just that I still get the beach ball but it's way less frequent.

> it’s possible that the garbage collection issue you’re experiencing with all sandboxes disabled is possibly ‘expected’. i’m not sure

Note that the profiles in #15 were without the sandbox disabled. But I don't know if that's actually related to the "content clog", which yes could be sandboxes for all I know.

**Comment by i3roly** [comment]
in light of our conversation, i’m pushing a few commits to put sub 10.10 platforms on GMP instead of VTdecoder.

it’s the cleanest way to fix the issue without fucking up the sandbox and preferences.

i don’t think the lord intended for you hungry hungry hippos to use VTdecoder.

or it’s just that firefox is too new and the OS is too old, where you cannot get it through without disabling the decoder.

i hope GMP acceleration is more than sufficient. it actually felt kinda faster than the vtdecoder but this could be selection bias.

Thanks,
Gagan

**Comment by Wowfunhappy** [comment]
Yes!!!! The new build is _so_ much better, this is the first time I've been able to actually just casually browse the web! Haven't run into an issue in 45 minutes of casual browsing.
